name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production Server via SSH
        env:
           IP ADDRESS
          PROD_HOST: ec2-54-82-50-131.compute-1.amazonaws.com
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # Connect using StrictHostKeyChecking=no to stop the verification error
          ssh -o StrictHostKeyChecking=no ubuntu@$PROD_HOST << EOF
            
            # 1. Stop and remove the old container
            sudo docker rm -f weather-app || true

            # 2. Login to Docker Hub
            sudo docker login -u $DOCKER_USER -p ${{ secrets.DOCKERHUB_TOKEN }}

            # 3. Pull the latest image
            sudo docker pull $DOCKER_USER/weather-app:latest

            # 4. Run the new container
            sudo docker run -d --name weather-app -p 80:5000 $DOCKER_USER/weather-app:latest
          EOF
