name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production Server via SSH
        env:
          PROD_HOST: ec2-54-82-50-131.compute-1.amazonaws.com
        run: |
          # Connect to the Prod Server
          ssh -o StrictHostKeyChecking=no ubuntu@$PROD_HOST << EOF
            
            # 1. Update the Deployment image
            kubectl set image deployment/weather-ml-app weather-ml-app=${{ secrets.DOCKERHUB_USERNAME }}/weather-app:latest

            # 2. Trigger a Rolling Restart (Zero Downtime)
            kubectl rollout restart deployment/weather-ml-app
            
            # 3. Wait for the update to finish successfully
            kubectl rollout status deployment/weather-ml-app
            
          EOF
