name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production Server via SSH
        env:
          PROD_HOST: ec2-54-237-12-65.compute-1.amazonaws.com
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          # Add Prod Server to known hosts to prevent verification errors
          ssh-keyscan -H $PROD_HOST >> ~/.ssh/known_hosts

          # Update the deployment using YOUR specific names:
          # Deployment: weather-ml-app
          # Container: weather-ml-app
          ssh ubuntu@$PROD_HOST "kubectl set image deployment/weather-ml-app weather-ml-app=$DOCKER_USER/weather-ml-app:${{ github.sha }} --record"

          # Verify the rollout status
          ssh ubuntu@$PROD_HOST "kubectl rollout status deployment/weather-ml-app"
